"""extend course table and add chapter table

Revision ID: 8641139b21f1
Revises: 49ac32ecf305
Create Date: 2018-05-29 19:56:30.456726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8641139b21f1'
down_revision = '49ac32ecf305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('video_url', sa.String(length=256), nullable=True))
    op.drop_column('chapters', 'viedo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('viedo_url', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('chapters', 'video_url')
    # ### end Alembic commands ###
